ConaviWeb/Controllers/CatController.cs
using ConaviWeb.Data.Repositories;
using ConaviWeb.Model;
using ConaviWeb.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using static ConaviWeb.Models.AlertsViewModel;

namespace ConaviWeb.Controllers
{
    public class CatController : Controller
    {
        private readonly ISourceFileRepository _sourceFileRepository;
        private readonly IUserRepository _userRepository;

        public CatController(ISourceFileRepository sourceFileRepository, IUserRepository userRepository)
        {
            _sourceFileRepository = sourceFileRepository;
            _userRepository = userRepository;
        }
        public IActionResult Index()
        {
            return View("../EFirma/_AddItem");
        }

        [HttpPost]
        public async Task<IActionResult> AddItem([FromForm] Partition partition)
        {
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            bool success = await _sourceFileRepository.InsertPartition(partition.Text, user, partition.JsonUsers, partition.Firmas);
            if (!success)
            {
                TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al registrar la partición");
                return RedirectToAction("Index", "UploadFile");
            }
            TempData["Alert"] = AlertService.ShowAlert(Alerts.Success, "Se registro con exito la partición");
            return RedirectToAction("Index","UploadFile");
        }


    }
}

ConaviWeb/Controllers/CreateUserController.cs
using ConaviWeb.Data.Repositories;
using ConaviWeb.Model.Request;
using ConaviWeb.Services;
using ConaviWeb.Tools;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static ConaviWeb.Models.AlertsViewModel;

namespace ConaviWeb.Controllers
{
    public class CreateUserController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly ISecurityTools _securityTools;
        public CreateUserController(IUserRepository userRepository, ISecurityTools securityTools)
        {
            _userRepository = userRepository;
            _securityTools = securityTools;
        }
        public IActionResult Index()
        {
            if (TempData.ContainsKey("Alert"))
                ViewBag.Alert = TempData["Alert"].ToString();
            return View("../EFirma/CreateUser");
        }
        public async Task<IActionResult> AddUserAsync(CreateUser user)
        {
            string spassword = _securityTools.GetSHA256(user.Password);
            user.Password = spassword;
            user.IdSistema = 5;
            user.IdRol = 4;
            try { 
            var success = await _userRepository.InsertUser(user);
            }
            catch
            {
                TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, "Ocurrio un error al registrarse o el email ya cuenta con registro previo.");
                return RedirectToAction("Index");
            }

            TempData["Alert"] = AlertService.ShowAlert(Alerts.Success, "Usuario registrado exitosamente.");
            return RedirectToAction("Index");
        }
    }
}

ConaviWeb/Controllers/EFirmaSatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ConaviWeb.Data.Repositories;
using ConaviWeb.Model;
using ConaviWeb.Model.Request;
using ConaviWeb.Model.Response;
using ConaviWeb.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using static ConaviWeb.Models.AlertsViewModel;

namespace ConaviWeb.Controllers
{
    [Authorize]
    [Route("EFirmaSat")]
    public class EFirmaSatController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IUserRepository _userRepository;
        private readonly IProcessSignRepository _processSignRepository;
        private readonly IProcessSigningService _processSigningService;
        public EFirmaSatController(IWebHostEnvironment environment, IUserRepository userRepository, IProcessSignRepository processSignRepository, IProcessSigningService processSigningService)
        {
            _environment = environment;
            _userRepository = userRepository;
            _processSignRepository = processSignRepository;
            _processSigningService = processSigningService;
        }
        public IActionResult Index()
        {
            return View("../EFirma/EFirmaSat");
        }

        [HttpPost]
        public ActionResult Index(string name)
        {
            //Send to the Index Action method which will prevent resubmission.
            return RedirectToAction("Index");
        }

        [Route("/EFirmaSat/SignFiles", Name = "Register")]
        public async Task<IActionResult> SignFiles([FromForm] DataSignRequest dataSignRequest)
        {
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            IEnumerable<FileResponse> files;
            bool success = false;
            Response respuesta = new();
            //if (user.Rol.ToString() == "FirmanteInterno")
            //{
                files = await _processSignRepository.GetFilesForSign(user.IdSystem, dataSignRequest.ArrayFiles, dataSignRequest.Estatus);
            //}
            //else
            //{
            //    files = await _processSignRepository.GetExternalFiles(user.Integrador);
            //}
            if (files.Any())
            {
                respuesta = await _processSigningService.ProcessFileSatAsync(user, dataSignRequest, files);
            }
            if (respuesta.Success == 0)
            {
                TempData["Alert"] = AlertService.ShowAlert(Alerts.Danger, respuesta.Message);
                //return View("../EFirma/Lista");
                return RedirectToAction("List","Lista");
            }

            TempData["Alert"] = AlertService.ShowAlert(Alerts.Success, "Se firmo " + files.Count() + " archivos.");
            //return View("../EFirma/Lista");
            return RedirectToAction("List", "Lista");
        }


    }
}

ConaviWeb/Controllers/FirmadosController.cs
using ConaviWeb.Data.Repositories;
using ConaviWeb.Model;
using ConaviWeb.Model.Response;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ConaviWeb.Controllers
{
    public class FirmadosController : Controller
    {
        private readonly ISecurityRepository _securityRepository;
        private readonly IUserRepository _userRepository;
        public FirmadosController(ISecurityRepository securityRepository, IUserRepository userRepository)
        {
            _securityRepository = securityRepository;
            _userRepository = userRepository;
        }
        public async Task<IActionResult> IndexAsync()
        {
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            IEnumerable<Partition> partitions = await _securityRepository.GetPartitionsD(user.IdSystem, user.Id);
            ViewData["Partitions"] = partitions;
            return View("../EFirma/Firmados");
        }
        public async Task<IActionResult> GetFirmadosAsync(int idParticion)
        {
            IEnumerable<Firmados> firmados = await _securityRepository.GetFirmados(idParticion);
            return Json(new { data = firmados });
        }
    }
}

ConaviWeb/Controllers/ListCancelController.cs
using ConaviWeb.Data.Repositories;
using ConaviWeb.Model;
using ConaviWeb.Model.Response;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ConaviWeb.Controllers
{
    [Authorize]
    [Route("ListCancel")]
    public class ListCancelController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IProcessSignRepository _processSignRepository;
        private readonly ISecurityRepository _securityRepository;
        public ListCancelController(IUserRepository userRepository, IProcessSignRepository processSignRepository, ISecurityRepository securityRepository)
        {
            _userRepository = userRepository;
            _processSignRepository = processSignRepository;
            _securityRepository = securityRepository;
        }

        [Route("List")]
        public async Task<IActionResult> Index()
        {
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            IEnumerable<Partition> partitions = await _securityRepository.GetPartitions(user.IdSystem);

            ViewData["Partitions"] = partitions;
            if (TempData.ContainsKey("Alert"))
                ViewBag.Alert = TempData["Alert"].ToString();
            return View("../EFirma/ListCancel");
        }

        [HttpGet("ListaFirmadosAjax/{idPartition?}")]
        public async Task<IActionResult> ListAllSigned(int idPartition)
        {
            Response response = new Response();
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            IEnumerable<FileResponse> files;

            //if (user.Rol.ToString() == "FirmanteInterno")
            //{
            if (idPartition == 0)
            {
                files = await _processSignRepository.GetSignedFilesCancel(user.IdSystem);
            }
            else
            {
                files = await _processSignRepository.GetPartitionFilesCancel(idPartition);
            }



            //}
            //else
            //{
            //    files = await _processSignRepository.GetExternalFiles(user.Integrador);
            //}

            if (files != null)
            {
                response.Success = 1;
                response.Message = "El usuario cuenta con " + files.Count() + " archivos";
                response.Data = files;
                return Json(new { data = files });
            }

            return BadRequest();
        }
    }
}

ConaviWeb/Controllers/ListaController.cs
using ConaviWeb.Data.Repositories;
using ConaviWeb.Model;
using ConaviWeb.Model.Response;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ConaviWeb.Controllers
{
    [Authorize]
    [Route("Lista")]
    public class ListaController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IProcessSignRepository _processSignRepository;

        public ListaController(IUserRepository userRepository, IProcessSignRepository processSignRepository)
        {
            _userRepository = userRepository;
            _processSignRepository = processSignRepository;
        }
        [Route("List")]
        public async Task<IActionResult> IndexAsync()
        {
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            TempData["Sistema"] = user.IdSystem;
            if (TempData.ContainsKey("Alert"))
                ViewBag.Alert = TempData["Alert"].ToString();
            return View("../EFirma/Lista");
        }

        [HttpGet("ListaAjax/{idEstatus?}")]
        public async Task<IActionResult> ListAllFiles(int IdEstatus)
        {
            Response response = new Response();
            User user = await _userRepository.GetUserDetails(Int32.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            IEnumerable<FileResponse> files;

            //if (user.Rol.ToString() == "FirmanteInterno")
            //{
                files = await _processSignRepository.GetFiles(user.Id,user.IdSystem, IdEstatus, Convert.ToInt32(user.Rol), user.RFC);


            //}
            //else
            //{
            //    files = await _processSignRepository.GetExternalFiles(user.Integrador);
            //}

            if (files != null)
            {
                response.Success = 1;
                response.Message = "El usuario cuenta con " + files.Count() + " archivos";
                response.Data = files;
                return Json(new { data=files });
            }

            return BadRequest();
        }

        [HttpGet("ListDetailAjax/{idPartition?}")]
        public async Task<IActionResult> ListDetailFiles(int idPartition)
        {
            Response response = new Response();
            IEnumerable<FileResponse> files;

            //if (user.Rol.ToString() == "FirmanteInterno")
            //{
            files = await _processSignRepository.GetPartitionSourceFiles(idPartition);


            //}
            //else
            //{
            //    files = await _processSignRepository.GetExternalFiles(user.Integrador);
            //}

            if (files != null)
            {
                response.Success = 1;
                response.Message = "El usuario cuenta con " + files.Count() + " archivos";
                response.Data = files;
                return Json(new { data = files });
            }

            return BadRequest();
        }
    }
}

ConaviWeb/Views/EFirma/CancelaSat.cshtml
@model ConaviWeb.Model.Request.DataSignRequest
@{
    ViewBag.Title = "Cancelación";
}
@*<div class="spinner" style="display:none">
    <div class="center-div">
        <div class="inner-div">
            <div class="loader"></div>
        </div>
    </div>
</div>*@

<div class="form-group row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <form id="formSign" class="submit-once" enctype="multipart/form-data" method="post" asp-route="Cancel">
                    <div class="alert alert-danger" asp-validation-summary="ModelOnly"><button class="close" data-dismiss="alert" aria-hidden="true">&times;</button></div>
                    <div class="form-group">
                        <label asp-for="KeySat"></label>
                        <input asp-for="KeySat" type="file" accept=".key">
                        <span asp-validation-for="KeySat" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CerSat"></label>

                        <input asp-for="CerSat" type="file" accept=".cer">
                        <span asp-validation-for="CerSat" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PassFirmante"></label>
                    </div>
                    <div class="form-group">
                        <input class="form-control" asp-for="PassFirmante" />
                        <span asp-validation-for="PassFirmante" class="text-danger"></span>
                    </div>
                    @*<label asp-for="ArrayFiles"></label>*@
                    <div class="form-group">
                        <input class="form-control" id="arrayCHK" type="hidden" asp-for="ArrayFiles" readonly />
                        <span asp-validation-for="ArrayFiles" class="text-danger"></span>
                    </div>
                    <button type="submit" id="btnFirma" class="btn btn-primary pull-right"><span class="fa fa-exclamation-triangle"></span>&ensp;Cancelar Firma</button>
                </form>
            </div>
        </div>
    </div>
</div>
        @section Scripts {@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}}

ConaviWeb/Views/EFirma/CreateUser.cshtml
@model ConaviWeb.Model.Request.CreateUser
@{
    Layout = "_Layout";
    ViewBag.Title = "Registro usuarios";
}
<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                @Html.Raw(@ViewBag.Alert)
            </div>
        </div>
        <form id="form_registro" asp-action="AddUser" asp-controller="CreateUser">
            <div class="modulos-dac  " id="RegistroUsrs">
                <div class="login-in top-buffer-x5">
                    <h4 id="nameSystem" style="text-align: center; margin-bottom: 25px;">Registro de usuarios</h4>
                    <hr class="red" />
                    <label>Nombre:</label>
                    <input placeholder="Escriba su nombre" id="nombres" asp-for="Nombre" type="text" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                    <br>
                    <label>Primer Apellido:</label>
                    <input placeholder="Escriba su primer Apellido" id="primerApe" asp-for="PApellido" type="text" class="form-control" />
                    <span asp-validation-for="PApellido" class="text-danger"></span>
                    <br>
                    <label>Segundo Apellido:</label>
                    <input placeholder="Escriba su segundo Apellido" id="segundoApe" asp-for="SApellido" type="text" class="form-control" />
                    <span asp-validation-for="SApellido" class="text-danger"></span>
                    <br />
                    <label> Correo electrónico:</label>
                    <input placeholder=" Especifica tu Correo Electrónico" id="correo" asp-for="Email" type="email" class="form-control" autocomplete="off" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                    <br>
                    <label>Usuario:</label>
                    <input placeholder="Especifica tu usuario" id="Usuario" asp-for="Usuario" type="text" class="form-control" autocomplete="off">
                    <span asp-validation-for="Usuario" class="text-danger"></span>
                    <br />
                    <label>Contraseña:</label>
                    <input placeholder="Especifica tu contraseña" id="Password" asp-for="Password" type="password" class="form-control" autocomplete="off">
                    <span asp-validation-for="Password" class="text-danger"></span>
                    <br>
                    <input placeholder="Confirma tu contraseña" id="ConfirmPassword" name="Password1" type="password" class="form-control" autocomplete="off">
                    <span id="msg"></span>
                    <br />
                    <label>RFC:</label>
                    <input type="text" id="rfc_input" style="width:100%;" asp-for="RFC" maxlength="14" oninput="validarInput(this)" class="form-control" placeholder="Ingrese su RFC">
                    <span asp-validation-for="RFC" class="text-danger"></span>
                    <span id="resultado"></span>
                    <span id="estatus"></span>
                    <br>
                    <label><i class="fas fa-user-alt gold"></i> DEPENDECIA</label>
                    <small id="lblDependecia" class="red-text gold hidden">Campo requerido *</small>
                    <select class="form-control" asp-for="Dependencia">
                        <option value="">----Seleciona-----</option>
                        <option value="1">CONAVI</option>
                        <option value="3">SEDATU</option>
                        <option value="4">SHCP</option>
                        <option value="5">INSUS</option>
                        <option value="6">SFP</option>
                        <option value="7">OIC</option>
                    </select>
                    <span asp-validation-for="Dependencia" class="text-danger"></span>
                    <div class="col-md-4">
                        <button type='submit' class="btn btn-primary .btn-xs text-center form-control top-buffer " id="btnSubmit">REGISTRAR</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>

@section Scripts {@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}}
<script>

    $(document).ready(function () {
        showAlert();
        $("#btnSubmit").attr("disabled", true);
        $("#ConfirmPassword").keyup(function () {
            if ($("#Password").val() != $("#ConfirmPassword").val()) {
                $("#msg").html("La contraseña no coincide").css("color", "#a94442").css("font-weight", "bold");
                $("#btnSubmit").attr("disabled", true);
            } else {
                $("#msg").html("La contraseña coincide").css("color", "#215d51").css("font-weight", "bold");
                $("#btnSubmit").attr("disabled", false);
            }
        });

    });

    function showAlert() {
        setTimeout(function () {
            $("#alerta").fadeOut(1500);

        }, 6000);


        setTimeout(function () {

            $("#alerta").remove();
        }, 12000);

    }

    function rfcValido(rfc, aceptarGenerico = true) {
        const re = /^([A-ZÑ&]{3,4}) ?(?:- ?)?(\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])) ?(?:- ?)?([A-Z\d]{2})([A\d])$/;
        var validado = rfc.match(re);

        if (!validado)  //Coincide con el formato general del regex?
            return false;

        //Separar el dígito verificador del resto del RFC
        const digitoVerificador = validado.pop(), rfcSinDigito = validado.slice(1).join(''), len = rfcSinDigito.length,

            //Obtener el digito esperado
            diccionario = "0123456789ABCDEFGHIJKLMN&OPQRSTUVWXYZ Ñ", indice = len + 1;
        var suma, digitoEsperado;

        if (len == 12) suma = 0
        else suma = 481; //Ajuste para persona moral

        for (var i = 0; i < len; i++)
            suma += diccionario.indexOf(rfcSinDigito.charAt(i)) * (indice - i);
        digitoEsperado = 11 - suma % 11;
        if (digitoEsperado == 11) digitoEsperado = 0;
        else if (digitoEsperado == 10) digitoEsperado = "A";

        //El dígito verificador coincide con el esperado?
        // o es un RFC Genérico (ventas a público general)?
        if ((digitoVerificador != digitoEsperado)
            && (!aceptarGenerico || rfcSinDigito + digitoVerificador != "XAXX010101000"))
            return false;
        else if (!aceptarGenerico && rfcSinDigito + digitoVerificador == "XEXX010101000")
            return false;
        return rfcSinDigito + digitoVerificador;
    }


    function validarInput(input) {
        var rfc = input.value.trim().toUpperCase(), resultado = document.getElementById("resultado"), valido;
        $("#rfc_input").val(rfc);
        var rfcCorrecto = rfcValido(rfc);   // ⬅️ Acá se comprueba

        if (rfcCorrecto) {
            valido = "Válido";
            resultado.classList.add("ok");
            $("#resultado").css("color", "#215d51").css("font-weight", "bold");
        } else {
            valido = "No válido"
            resultado.classList.remove("ok");
            $("#resultado").css("color", "#a94442").css("font-weight", "bold");
        }

        resultado.innerText = "\RFC: " + valido;
    }




    $('#rfc_input').on('keypress', function (e) {
        if (e.which == 32) {
            console.log('Space Detected');
            return false;
        }

    });


</script>

ConaviWeb/Views/EFirma/_AddItems.cshtml
@model ConaviWeb.Model.Partition
<script src="~/js/jquery-1.11/jquery.min.js" type="text/javascript"></script>

<form id="formPartition" method="post" asp-controller="Cat" asp-action="AddItem">
    <div class="alert alert-danger" asp-validation-summary="ModelOnly"><button class="close" data-dismiss="alert" aria-hidden="true">&times;</button></div>
    @*<div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">Agregar nueva partición</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Text"></label>
                    <input id="partitionText" class="form-control" asp-for="Text" autocomplete="off" />
                    <span asp-validation-for="Text" class="text-danger"></span>

                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>*@
    

        <div class='modal-header'>
            <h4 id='titulo-modal' style="font-weight: 300">Agregar nueva partición</h4>
        </div>
        <div class='modal-body'>
            <div class="row col-md-12">
                <label asp-for="Text" style="font-size:18px"></label>
                <input id="partitionText" class="form-control" asp-for="Text" autocomplete="off" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            @if (ViewBag.Sistema == 5)
            {
                <div class="row col-md-12">
                    <label style="font-size:18px">Usuario</label>
                    <select id="slctUser" class="form-control" asp-items="@(new SelectList((System.Collections.IEnumerable)ViewData["Users"], "Id", "Name"))">
                        <option value="0">--Select--</option>
                    </select>
                </div>
                <div class="row col-md-12">
                    <label style="font-size:18px">Función dentro del Comité</label>
                    <input type="text" id="funcText" class="form-control" />
                </div>
                <div class="row col-md-12">
                    <label style="font-size:18px">Nombramiento</label>
                    <input type="text" id="nombramiento" class="form-control" />
                </div>
                <div class="row col-md-6" style="margin-top: 25px;">
                    <button type="button" id="btnAdd" class="btn btn-danger"><i class="fa fa-plus"></i></button>
                    <button type="button" id="btnRemove" class="btn btn-primary"><i class="fa fa-minus"></i></button>
                </div>
                <div class="row col-md-12">
                    <span asp-validation-for="JsonUsers" class="text-danger"></span>
                    <div class="addTask">
                        <table class="tableUsers table table-striped" style="width: 100%; font-size: 13px">
                            <thead>
                                <tr>
                                    <th>Usuario</th>
                                    <th style="text-align:center">Posición firma</th>
                                    <th style="text-align:center">Nombramiento</th>
                                    <th style="text-align:center">Función</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
                <input asp-for="JsonUsers" style="visibility:hidden" />
                <input asp-for="Firmas" style="visibility:hidden" />
            }
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" id="btnCan">Cancelar</button>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
</form>



@section scripts{@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}}

<script>
    $(document).ready(function () {
        var json = [];
        var jsonString;
        var i = 0;
        $('#btnAdd').click(function () {
            //i++;
            var idUser = $('#slctUser').val();
            var arrName=$('#slctUser option:selected').text().split("-");
            var name = arrName[0];
            var cargo = $('#funcText').val();
            var puesto = $('#nombramiento').val();
            
            if (idUser > 0 && cargo !='') {
                i++;
                json.push({
                    id_usuario: idUser,
                    posicion: i,
                    cargo: cargo,
                    puesto: puesto
                });
                var fixingContent =
                    '<tr><td>' + name + '</td>' + '<td style="text-align:center">' + i + '</td>' + '<td style="text-align:center">' + puesto +'</td>' + '<td style="text-align:center">'+ cargo +'</td></tr>';
                $('.tableUsers').append(fixingContent);
                $('#slctUser').val(0);
                $('#funcText').val('');
                $('#nombramiento').val('');
                
                jsonString = JSON.stringify(json);
                $('#JsonUsers').val(jsonString);
                $('#Firmas').val(i);
                console.log("JSON: ", jsonString, " FIRMAS", i)
            }
        })
        $('#btnRemove').click(function () {
            json = [];
            jsonString = '';
            $('#slctUser').val(0);
            $('#funcText').val('');
            $('#nombramiento').val('');
            $(".tableUsers > tbody").html('');
            $('#JsonUsers').val('');
            $('#Firmas').val('');
            i = 0;
        })
        $('#btnCan').click(function () {
            json = [];
            jsonString = '';
            $('#slctUser').val(0);
            $('#funcText').val('');
            $('#nombramiento').val('');
            $(".tableUsers > tbody").html('');
            $('#JsonUsers').val('');
            $('#Firmas').val('');
            $('#partitionText').val('');
            i = 0;
        })
        $("#slctUser").on("change", function () {
            let option = $("#slctUser option:selected").text();
            let funct = option.split("-");
            $('#funcText').val($.trim(funct[1]));
            $('#nombramiento').val($.trim(funct[2]));
        });
    })
</script>

ConaviWeb/Views/EFirma/_ListaCargados.cshtml
@{
    ViewBag.Title = "Lista Cargados";
}
    <form id="formTable">
        <table id="table" class="table">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        RUTA
                    </th>
                    <th>
                        NOMBRE
                    </th>
                    <th>
                        FECHA CARGA
                    </th>
                    <th>
                        ESTATUS
                    </th>
                    <th>
                        DETALLE
                    </th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </form>
<br />
<br />
<br />